var rawData = {
  "error_code": 1,
  "response_string": "OK",
  "data": [
    {
      "markets": {
        "id": "2",
        "name": "Chandni Chowk Market",
        "state": "1",
        "city": "1",
        "address": "Chandani chowk",
        "latitude": "28.6506000",
        "longitude": "77.2303000",
        "show_default": "YES",
        "image": "[{\"image\":\"uploads\\\/d205e0f7be90233918b271961899b0d61.png\",\"id\":1}]",
        "created_at": "2022-03-02 03:38:03",
        "updated_at": "2022-03-02 03:38:03",
        "deleted_at": null
      },
      "shops": [
        {
          "shop": {
            "id": "4",
            "user_id": "9",
            "shop_name": "Sabhya Bridal Wears",
            "slug_name": "",
            "gst_number": "07ACWFS6103Q1Z9",
            "shop_number": "1862-A",
            "street": "Main Road ",
            "landmark": null,
            "city": "New Delhi",
            "state": "Delhi",
            "country": "India",
            "pincode": "110006",
            "google_address": "J-27, Oldanpur, Navin Shahdara, Shahdara, New Delhi, Delhi 110032, India",
            "latitude": "28.6761381",
            "longitude": "77.2833278",
            "open_time": "10:00:00",
            "close_time": "19:00:00",
            "delivery_range": "0.00",
            "description": "We are a shop in Chandni chowk. we are committed to serve our customers.",
            "current_subscription_id": "",
            "qr_image": null,
            "image": "[{\"image\":\"uploads\\\/7e2b9a32f137aa902d7600027d420d72.jpg\",\"id\":1,\"extension\":null}]",
            "market_id": "2",
            "is_shop_closed": "NO",
            "is_self_delivered": "NO",
            "is_auto_accept": "NO",
            "gst_image": null,
            "shop_days": "[\"Monday\",\"Tuesday\",\"Wednesday\",\"Thrusday\",\"Friday\",\"Saturday\"]",
            "created_at": "2022-03-02 08:49:28",
            "updated_at": "2022-03-02 08:49:28",
            "deleted_at": null
          },
          "offers": "0",
          "status": "CLOSED",
          "ratings": null,
          "categories": [
            {
              "id": "1",
              "category_type": "SHOP",
              "name": "Appliances & Electronics",
              "slug": "",
              "parent_id": null,
              "commission": "4.00",
              "image": "[{\"image\":\"uploads\\\/7b6fbd4c592d356e087a0f10537510072.png\",\"id\":1}]",
              "created_at": "2022-03-02 02:34:08",
              "updated_at": "2022-03-02 02:34:08",
              "deleted_at": null
            }
          ],
          "shopkeeper": {
            "id": "9",
            "first_name": "Abhishek ",
            "last_name": "Gupta",
            "email": "sabhyabridalwears@gmail.com ",
            "phone": "9871341112",
            "app_key": "6e5e3f7b9d633ddbefcdff09ad7ecf3f",
            "dob": null,
            "age": "0",
            "gender": "MALE",
            "image": null,
            "fcm_token": null,
            "aadhaar_number": "000000000000",
            "aadhaar_front": null,
            "aadhaar_back": null,
            "pan_number": "0000000000",
            "pan_image": null,
            "fb_login": null,
            "gmail_login": null,
            "user_type": "SK",
            "password": "d5018c3e00f3c4aa892acdfde1fd0511",
            "is_verified": "VERIFIED",
            "is_kyc": "NO",
            "referal_code": "PT279",
            "google_address": null,
            "latitude": "0.0000000",
            "longitude": "0.0000000",
            "created_at": "2022-03-02 08:40:05",
            "updated_at": "2022-03-02 08:40:05",
            "deleted_at": null
          }
        },
        {
          "shop": {
            "id": "14",
            "user_id": "22",
            "shop_name": "Make in India",
            "slug_name": "",
            "gst_number": "07AAAPK8250C2Z2",
            "shop_number": "1495",
            "street": "Main Road",
            "landmark": null,
            "city": "New Delhi",
            "state": "Delhi",
            "country": "India",
            "pincode": "110006",
            "google_address": "1495, main road, SBI heritage building, Chandni chowk, delhi-110006",
            "latitude": "28.6761445",
            "longitude": "77.2833270",
            "open_time": "10:00:00",
            "close_time": "19:00:00",
            "delivery_range": "0.00",
            "description": "We are a shop in Chandni chowk. we are committed to serve our customers.",
            "current_subscription_id": "",
            "qr_image": null,
            "image": "[{\"image\":\"uploads\\\/7e2b9a32f137aa902d7600027d420d72.jpg\",\"id\":1,\"extension\":null}]",
            "market_id": "2",
            "is_shop_closed": "NO",
            "is_self_delivered": "NO",
            "is_auto_accept": "NO",
            "gst_image": null,
            "shop_days": "[\"Monday\",\"Tuesday\",\"Wednesday\",\"Thrusday\",\"Friday\",\"Saturday\",\"Sunday\"]",
            "created_at": "2022-03-02 11:55:52",
            "updated_at": "2022-03-02 11:55:52",
            "deleted_at": null
          },
          "offers": "0",
          "status": "CLOSED",
          "ratings": null,
          "categories": [
            {
              "id": "1",
              "category_type": "SHOP",
              "name": "Appliances & Electronics",
              "slug": "",
              "parent_id": null,
              "commission": "4.00",
              "image": "[{\"image\":\"uploads\\\/7b6fbd4c592d356e087a0f10537510072.png\",\"id\":1}]",
              "created_at": "2022-03-02 02:34:08",
              "updated_at": "2022-03-02 02:34:08",
              "deleted_at": null
            }
          ],
          "shopkeeper": {
            "id": "22",
            "first_name": "Gopal ",
            "last_name": "Jindal",
            "email": "makeinindia1960@hotmail.com",
            "phone": "9990440440",
            "app_key": "d83808ff202c215adfab6ec707d291c7",
            "dob": null,
            "age": "0",
            "gender": "MALE",
            "image": null,
            "fcm_token": null,
            "aadhaar_number": "000000000000",
            "aadhaar_front": null,
            "aadhaar_back": null,
            "pan_number": "0000000000",
            "pan_image": null,
            "fb_login": null,
            "gmail_login": null,
            "user_type": "SK",
            "password": "d5018c3e00f3c4aa892acdfde1fd0511",
            "is_verified": "VERIFIED",
            "is_kyc": "NO",
            "referal_code": "PT9222",
            "google_address": null,
            "latitude": "0.0000000",
            "longitude": "0.0000000",
            "created_at": "2022-03-02 11:52:43",
            "updated_at": "2022-03-02 11:52:43",
            "deleted_at": null
          }
        },
      ]
    },
  ],
  "data1": null,
  "data2": null,
  "data3": null
};
